#!/bin/sh
if [ $1 = "test" ]; then
    shift
    pytest "$@"
else
    if [ "$ENV" = "prod" ]; then
        echo "Starting in production mode"
        gunicorn -w 4 -b 0.0.0.0:8000 stormtracker.app:app
    else
        echo "Starting in development mode"
        FLASK_DEBUG=1 FLASK_APP=stormtracker.app python -m flask run -h 0.0.0.0 -p 8000
    fi
fi
