services:
  app:
    build: .
    environment:
      PORT: ${PORT:-8000}
      ENV: ${ENV:-dev}
      ROOT_URL: ${ROOT_URL}
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
    volumes:
      - .:/app/
    ports:
      - ${PORT:-8000}:8000
  redis:
    image: redis:latest
